# Autogenerated wrapper script for LAGraph_jll for i686-w64-mingw32
export liblagraph, liblagraphx

using SSGraphBLAS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("LAGraph")
JLLWrappers.@declare_library_product(liblagraph, "liblagraph.dll")
JLLWrappers.@declare_library_product(liblagraphx, "liblagraphx.dll")
function __init__()
    JLLWrappers.@generate_init_header(SSGraphBLAS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        liblagraph,
        "bin\\liblagraph.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblagraphx,
        "bin\\liblagraphx.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
