# Autogenerated wrapper script for LAGraph_jll for x86_64-unknown-freebsd
export liblagraph, liblagraphx

using SSGraphBLAS_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("LAGraph")
JLLWrappers.@declare_library_product(liblagraph, "liblagraph.so.1")
JLLWrappers.@declare_library_product(liblagraphx, "liblagraphx.so.1")
function __init__()
    JLLWrappers.@generate_init_header(SSGraphBLAS_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        liblagraph,
        "lib/liblagraph.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblagraphx,
        "lib/liblagraphx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
